// Interface automatically generated by schemas-to-ts

import { Player } from '../../../player/content-types/player/player';
import { Player_Plain } from '../../../player/content-types/player/player';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Clan {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    name?: string;
    tag?: string;
    players: { data: Player[] };
  };
}
export interface Clan_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  tag?: string;
  players: Player_Plain[];
}

export interface Clan_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  tag?: string;
  players: number[];
}

export interface Clan_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  tag?: string;
  players: AdminPanelRelationPropertyModification<Player_Plain>;
}
