// Interface automatically generated by schemas-to-ts

import { Match } from '../../../match/content-types/match/match';
import { Player } from '../../../player/content-types/player/player';
import { Match_Plain } from '../../../match/content-types/match/match';
import { Player_Plain } from '../../../player/content-types/player/player';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface PlayerMatch {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    match?: { data: Match };
    player?: { data: Player };
    placement?: number;
    score?: number;
    kills?: number;
    deaths?: number;
    assists?: number;
    damage?: number;
    headshots?: number;
    shots?: number;
    hits?: number;
    highestKillStreak?: number;
    playerUtcConnectTimeSeconds?: number;
    playerUtcDisconnectTimeSeconds?: number;
    killDeathRatio?: string;
  };
}
export interface PlayerMatch_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  match?: Match_Plain;
  player?: Player_Plain;
  placement?: number;
  score?: number;
  kills?: number;
  deaths?: number;
  assists?: number;
  damage?: number;
  headshots?: number;
  shots?: number;
  hits?: number;
  highestKillStreak?: number;
  playerUtcConnectTimeSeconds?: number;
  playerUtcDisconnectTimeSeconds?: number;
  killDeathRatio?: string;
}

export interface PlayerMatch_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  match?: number;
  player?: number;
  placement?: number;
  score?: number;
  kills?: number;
  deaths?: number;
  assists?: number;
  damage?: number;
  headshots?: number;
  shots?: number;
  hits?: number;
  highestKillStreak?: number;
  playerUtcConnectTimeSeconds?: number;
  playerUtcDisconnectTimeSeconds?: number;
  killDeathRatio?: string;
}

export interface PlayerMatch_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  match?: AdminPanelRelationPropertyModification<Match_Plain>;
  player?: AdminPanelRelationPropertyModification<Player_Plain>;
  placement?: number;
  score?: number;
  kills?: number;
  deaths?: number;
  assists?: number;
  damage?: number;
  headshots?: number;
  shots?: number;
  hits?: number;
  highestKillStreak?: number;
  playerUtcConnectTimeSeconds?: number;
  playerUtcDisconnectTimeSeconds?: number;
  killDeathRatio?: string;
}
