// Interface automatically generated by schemas-to-ts

import { Player } from '../../../player/content-types/player/player';
import { PlayerMatch } from '../../../player-match/content-types/player-match/player-match';
import { Player_Plain } from '../../../player/content-types/player/player';
import { PlayerMatch_Plain } from '../../../player-match/content-types/player-match/player-match';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Match {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    matchId: string;
    map?: string;
    mapName?: string;
    mode?: string;
    players?: { data: Player[] };
    player_match_stats: { data: PlayerMatch[] };
    axisScore?: number;
    alliesScore?: number;
    utcStartTime?: string;
    utcEndTime?: string;
    teamAxis?: any;
    teamAllies?: any;
  };
}
export interface Match_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  matchId: string;
  map?: string;
  mapName?: string;
  mode?: string;
  players?: Player_Plain[];
  player_match_stats: PlayerMatch_Plain[];
  axisScore?: number;
  alliesScore?: number;
  utcStartTime?: string;
  utcEndTime?: string;
  teamAxis?: any;
  teamAllies?: any;
}

export interface Match_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  matchId: string;
  map?: string;
  mapName?: string;
  mode?: string;
  players?: number[];
  player_match_stats: number[];
  axisScore?: number;
  alliesScore?: number;
  utcStartTime?: string;
  utcEndTime?: string;
  teamAxis?: any;
  teamAllies?: any;
}

export interface Match_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  matchId: string;
  map?: string;
  mapName?: string;
  mode?: string;
  players?: AdminPanelRelationPropertyModification<Player_Plain>;
  player_match_stats: AdminPanelRelationPropertyModification<PlayerMatch_Plain>;
  axisScore?: number;
  alliesScore?: number;
  utcStartTime?: string;
  utcEndTime?: string;
  teamAxis?: any;
  teamAllies?: any;
}
